# Generated by Django 3.1.4 on 2021-07-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='txn_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
