# Generated by Django 3.1.4 on 2020-12-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='placed',
            field=models.BooleanField(default='False'),
        ),
    ]
