# Generated by Django 3.1.4 on 2021-01-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='defaultt.jpg', upload_to='product_images'),
        ),
    ]
