# Generated by Django 3.1.4 on 2021-01-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_prod.jpg', upload_to='profile_pics'),
        ),
    ]
