# Generated by Django 3.1.4 on 2021-07-17 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction_txn_id'),
        ('products', '0017_auto_20210111_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.transaction'),
        ),
    ]
